require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/tasks/**/*'

  Exclude:
    - 'db/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Lint/HandleExceptions:
  Exclude:
    - 'bin/*'

Metrics/AbcSize:
  Max: 15

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/DescribeClass:
  Exclude:
    - 'spec/i18n_spec.rb'

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 100

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
  EnforcedHashRocketStyle: table

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4
